In [ ]:
# Group 09
# Pecho, Rossana
# Rodas, Ulises
# Villacorta, Bruno
# Villena, Pedro

In [ ]:
# 1. Explain the difference between working on a branch and working directly on main.
# Why is it recommended to always use branches in collaborative projects?

# Working directly on main means you are changing the primary production code, which should always remain stable and ready for deployment. 
# In contrast, working on a branch allows you to develop, test, and fix issues in an isolated environment without affecting the main codebase.

# It is recommended to always use branches in collaborative projects because they prevent breaking the main code, allow team members to work 
# independently, make code reviews easier, and keep the project organized and safe.

In [36]:
# 6. Declare a variable for each of the following types: int, float, string, and boolean. - Rossana
# Then print the type of each variable using the type() function 
variable_list=[3, 4.0 , "Caravana", 5<3]

for i in variable_list:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [15]:
# 7. Create a list that contains the following elements: - Pedro
# A string
# A boolean value
# Two numeric values (of any type)
# A list with two strings representing your favorite music artists 

list_pedro = ["Manzana", True, 26, 6.3, ["Alex Turner", "León Larregui"]] 
print(list_pedro)

# From that list:

# Access the first and the last element
print(list_pedro[0])
print(list_pedro[4][1])

# Add a new string
list_pedro.append("Papaya")
print(list_pedro)

# Remove the boolean value
list_pedro.remove(True)
print(list_pedro)

['Manzana', True, 26, 6.3, ['Alex Turner', 'León Larregui']]
Manzana
León Larregui
['Manzana', True, 26, 6.3, ['Alex Turner', 'León Larregui'], 'Papaya']
['Manzana', 26, 6.3, ['Alex Turner', 'León Larregui'], 'Papaya']


In [2]:
# 8. Define a tuple that contains: [1 pts] - Bruno

# A string
# A boolean
# A tuple with three numeric values (of any type)

# Explain in your own words why a tuple is immutable and try to modify one of its elements to prove it.

# Define the tuple
my_tuple = ("Hello", True, (3.1415, 2.7183, 17))

#Explanation: A tuple is immutable because once it is created, it cannot be modified. This means you cannot change, add, or remove elements from a tuple after it is defined.
#Trying to modify an element of the tuple
my_tuple[0] = ("Goodbye")
#This will raise an error" 

TypeError: 'tuple' object does not support item assignment

In [3]:
# 9. Write a Python function named movie_summary that takes as argument a dictionary of movies - Ulises
#Iteramos:
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        year = info["year"]
        genre = info["genre"]
        sentence = f"The movie {title} belongs to the {genre} genre and was released in {year}."
        summaries.append(sentence)
    return summaries


# Diccionario con las 3 películas
movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

# Ejecutamos la función
result = movie_summary(movies)

# Mostramos cada frase en pantalla
for sentence in result:
    print(sentence)

# The function must return a list with sentences in the following format:
# "The movie Inception belongs to the Sci-Fi genre and was released in 2010."

The movie Inception belongs to the Sci-Fi genre and was released in 2010.
The movie Parasite belongs to the Drama genre and was released in 2019.
The movie Whiplash belongs to the Drama genre and was released in 2014.


In [32]:
# 10. Using NumPy, generate a 4x4 matrix with random integers between 1 and 100. - Rossana
# Then calculate:
# * The mean per column
# * The sum of the values in the main diagonal
import numpy as np

matrix = np.random.randint(1, 101, size = (4, 4))
print("Matriz:\n", matrix)

#Media por columna:
print("\nMedia por columna:", matrix.mean(axis=0))

#Suma de la diagonal principal:
print("Suma diagonal:", np.trace(matrix))

Matriz:
 [[83 40 56 19]
 [21 61 38 73]
 [88 26  9 45]
 [91 58 92 52]]

Media por columna: [70.75 46.25 48.75 47.25]
Suma diagonal: 205


In [33]:
# 11. From the list of grades [15, 17, 20, 11, 13, 18, 19], create a Pandas Series assigning student names as the index - Pedro
# (for example: "Ana", "Jorge", "Valeria", etc.).

import pandas as pd

list_grades = [15, 17, 20, 11, 13, 18, 19]
list_students = ["Rosanna", "Ulises", "Bruno", "Pedro", "Luis", "Jorge", "Alejandra"]

data_grades = pd.Series( list_grades, index = list_students )
data_grades

Rosanna      15
Ulises       17
Bruno        20
Pedro        11
Luis         13
Jorge        18
Alejandra    19
dtype: int64

In [34]:
# 12. Using the Series created in the previous step, calculate: - Bruno

# * The average of the grades.
# * The student with the highest grade (use .idxmax()).
# * The student with the lowest grade (use .idxmin()).

average_grade = data_grades.mean()
highest_grade_student = data_grades.idxmax()
lowest_grade_student = data_grades.idxmin()

# Display results:
print("Average Grade:", average_grade)
print("Student with the highest grade is:", highest_grade_student)
print("Student with the lowest grade is:", lowest_grade_student)

Average Grade: 16.142857142857142
Student with the highest grade is: Bruno
Student with the lowest grade is: Pedro


In [7]:
# 13. Create a Series from a dictionary of countries and their capitals. - Ulises
# Filter and display only those countries whose capital has more than 6 letters.
import pandas as pd
datos = {
    "Brasil": "Brasilia",
    "Alemania": "Berlin",
    "Japon": "Tokio",
    "Mexico": "Mexico D.F.",
    "Peru": "Lima",
    "Bolivia": "Sucre",
    "Inglaterra": "Londres",
    "Egipto": "El Cairo",
}

paises = pd.Series(datos)

six_len = paises[paises.str.len() > 6]

print(six_len)

Brasil           Brasilia
Mexico        Mexico D.F.
Inglaterra        Londres
Egipto           El Cairo
dtype: object


In [37]:
# 14. Create a Series containing several strings and convert all its elements to uppercase using the .apply(str.upper) method. - Pedro
import pandas as pd

months = pd.Series(["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"])

upper_months = months.apply(str.upper)
print(upper_months) 

0       JANUARY
1      FEBRUARY
2         MARCH
3         APRIL
4           MAY
5          JUNE
6          JULY
7        AUGUST
8     SEPTEMBER
9       OCTOBER
10     NOVEMBER
11     DECEMBER
dtype: object
