In [ ]:
# Parte 2A: Data Types & List/Tuple

In [ ]:
# 1) Declarar variables int, float, string, bool
edad = 25                 # int
altura = 1.78             # float
nombre = "Freddy"         # string
es_estudiante = True      # bool

In [ ]:
# 2) Imprimir type() de cada una
print("Tipos de variables:")
print(type(edad), type(altura), type(nombre), type(es_estudiante), "\n")

Tipos de variables:
<class 'int'> <class 'float'> <class 'str'> <class 'bool'> 



In [ ]:
# 3) Crear una lista con los elementos pedidos (puedes mezclar tipos)
mi_lista = [edad, altura, nombre, es_estudiante]
print("Lista inicial:", mi_lista)

Lista inicial: [25, 1.78, 'Freddy', True]


In [ ]:
# 4) Acceder al primer y último elemento
print("Primer elemento:", mi_lista[0])   # índice 0
print("Último elemento:", mi_lista[-1], "\n")  # índice negativo

Primer elemento: 25
Último elemento: True 



In [ ]:
# 5) Añadir un string a la lista
mi_lista.append("Python")
print("Después de append('Python'):", mi_lista)

Después de append('Python'): [25, 1.78, 'Freddy', True, 'Python']


In [ ]:
# 6) Remover el booleano (True) de la lista
# remove() elimina la primera aparición del valor dado
mi_lista.remove(True)
print("Después de remove(True):", mi_lista, "\n")

Después de remove(True): [25, 1.78, 'Freddy', 'Python'] 



In [ ]:
# 7) Definir un tuple con: string, boolean, y una tuple numérica
tupla_numerica = (10, 20, 30)
mi_tupla = ("dato_texto", False, tupla_numerica)
print("Tupla:", mi_tupla)

Tupla: ('dato_texto', False, (10, 20, 30))


In [ ]:
# 8) Explicar inmutabilidad y demostrar error:
# Las tuplas son INMUTABLES: no puedes reasignar, añadir o borrar elementos.
# Intento de modificar un elemento -> TypeError
try:
    mi_tupla[0] = "otro_texto"   # Esto debe fallar
except TypeError as e:
    print("\nDemostración de inmutabilidad:")
    print("No se puede modificar una tupla. Error capturado:", e)


Demostración de inmutabilidad:
No se puede modificar una tupla. Error capturado: 'tuple' object does not support item assignment


# Función que recibe un diccionario de películas

In [1]:
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        sentence = f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}."
        summaries.append(sentence)
    return summaries

# Diccionario con las películas del grupo
movies = {
    "Orgullo y prejuicio": {"year": 2005, "genre": "Romance/Drama"},
    "Pingüinos de papá": {"year": 2011, "genre": "Comedia/Familiar"},
    "Legalmente rubia": {"year": 2001, "genre": "Comedia"}
}

# Probar la función
movie_summary(movies)

['The movie Orgullo y prejuicio belongs to the Romance/Drama genre and was released in 2005.',
 'The movie Pingüinos de papá belongs to the Comedia/Familiar genre and was released in 2011.',
 'The movie Legalmente rubia belongs to the Comedia genre and was released in 2001.']

# Función que recibe un diccionario de películas

In [1]:

import numpy as np

# Generar matriz 4x4 con enteros aleatorios entre 1 y 100
matrix = np.random.randint(1, 101, size=(4,4))
print("Matriz generada:\n", matrix)

# Calcular la media por columna
mean_per_column = np.mean(matrix, axis=0)
print("\nMedia por columna:", mean_per_column)

# Calcular la suma de la diagonal principal
sum_diagonal = np.trace(matrix)
print("\nSuma de la diagonal principal:", sum_diagonal)

Matriz generada:
 [[71 92 19 80]
 [ 9 93 47 21]
 [77 93 12 73]
 [18 61 84 94]]

Media por columna: [43.75 84.75 40.5  67.  ]

Suma de la diagonal principal: 270


# Part 3 - Panda Series

## Creating the Panda series

In [53]:
import pandas as pd
import numpy as np

In [54]:
grades = [15, 17, 20, 11, 13, 18, 19]
grades

[15, 17, 20, 11, 13, 18, 19]

In [55]:
names = ["Ana", "Jorge", "Valeria", "Pedro", "Santiago", "Juan", "Esteban"]
names

['Ana', 'Jorge', 'Valeria', 'Pedro', 'Santiago', 'Juan', 'Esteban']

In [56]:
studentgrades = pd.Series(grades, index = names)
studentgrades

Ana         15
Jorge       17
Valeria     20
Pedro       11
Santiago    13
Juan        18
Esteban     19
dtype: int64

### Now I will calculate the average grade from the Panda series.

In [57]:
studentgrades

Ana         15
Jorge       17
Valeria     20
Pedro       11
Santiago    13
Juan        18
Esteban     19
dtype: int64

In [58]:
avg = studentgrades.mean()
avg

np.float64(16.142857142857142)

### The average grade is 16.142857142857142

In [31]:
highestgr = studentgrades.idxmax()
highestgr

'Valeria'

### The student with the highest grade is Valeria.

In [59]:
lowestgr = studentgrades.idxmin()
lowestgr

'Pedro'

### The student with the lowest grade is Pedro.

### Now I will create a dictionary of countries and capitals.

In [60]:
co_dic = {"Indonesia": "Jakarta",
          "Argentina": "Buenos Aires",
          "Canada": "Ottawa",
          "Iraq": "Baghdad",
          "China": "Beijing",
          "Chile": "Santiago",
          "Ethiopia": "Addis Adaba",
          "France": "Paris"}
co_dic

{'Indonesia': 'Jakarta',
 'Argentina': 'Buenos Aires',
 'Canada': 'Ottawa',
 'Iraq': 'Baghdad',
 'China': 'Beijing',
 'Chile': 'Santiago',
 'Ethiopia': 'Addis Adaba',
 'France': 'Paris'}

In [61]:
count = pd.Series(co_dic)
count

Indonesia         Jakarta
Argentina    Buenos Aires
Canada             Ottawa
Iraq              Baghdad
China             Beijing
Chile            Santiago
Ethiopia      Addis Adaba
France              Paris
dtype: object

I will display only those whose capitals have more than six letters.

In [62]:
count[count.str.len() > 6]

Indonesia         Jakarta
Argentina    Buenos Aires
Iraq              Baghdad
China             Beijing
Chile            Santiago
Ethiopia      Addis Adaba
dtype: object

### I will create a Series with several strings and convert all its elements to uppercase

In [63]:
series = pd.Series(["first","second","third","fourth","fifth","sixth","seventh","eighth","ninth","tenth"])
series

0      first
1     second
2      third
3     fourth
4      fifth
5      sixth
6    seventh
7     eighth
8      ninth
9      tenth
dtype: object

In [64]:
series=series.apply(str.upper)

In [65]:
series

0      FIRST
1     SECOND
2      THIRD
3     FOURTH
4      FIFTH
5      SIXTH
6    SEVENTH
7     EIGHTH
8      NINTH
9      TENTH
dtype: object

Now the Series is un uppercase.