## TAREA 1 - Parte 2


In [1]:
# Pregunta 6. Declaramos una variable de cada tipo:
entero = 10            #int
decimal = 3.14         #float
texto = "Buenos días"  #string
booleano = True        #booleano

In [2]:
# Mostramos las variables
print(type(entero))   
print(type(decimal))  
print(type(texto))   
print(type(booleano)) 

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [3]:
# Pregunta 7. Creamos una lista:
equipo_10 = [
    "Equipo",                # string
    True,                    # booleano
    10,                      # número entero
    3.14,                    # número decimal
    ["Shakira", "Miranda"]     # lista con dos strings
]

In [4]:
# Accedemos al primer elemento:
print("Primer elemento:", equipo_10[0])

Primer elemento: Equipo


In [5]:
# Accedemos al último elemento
print("Último elemento:", equipo_10[-1])

Último elemento: ['Shakira', 'Miranda']


In [6]:
# Agregamos un nuevo string
equipo_10.append("Katty Perry")
print("Lista después de agregar un string:", equipo_10)

Lista después de agregar un string: ['Equipo', True, 10, 3.14, ['Shakira', 'Miranda'], 'Katty Perry']


In [7]:
# Eliminamos el valor booleano
equipo_10.remove(True)
print("Lista después de eliminar el booleano:", equipo_10)

Lista después de eliminar el booleano: ['Equipo', 10, 3.14, ['Shakira', 'Miranda'], 'Katty Perry']


In [8]:
# Pregunta 8. Definiendo una Tuple

In [9]:
tuple_1 = ("Perú", False, (5,7.5, 2.14))
print(tuple_1)

('Perú', False, (5, 7.5, 2.14))


In [10]:
# Pregunta 8. Explicando por qué una Tuple es inmutable
rpta_8 = """"Una tupla es inmutable por construcción de python, es decir, 
la tupla ya viene configurada por python para que, una vez creada una determinada tupla no se puedan modificar los datos, 
lo cual garantiza la seguridad, estabilidad, e integridad de los datos de la tupla, y así los datos no serán
modificados, añadidos, o eliminados."""
print (rpta_8)


"Una tupla es inmutable por construcción de python, es decir, 
la tupla ya viene configurada por python para que, una vez creada una determinada tupla no se puedan modificar los datos, 
lo cual garantiza la seguridad, estabilidad, e integridad de los datos de la tupla, y así los datos no serán
modificados, añadidos, o eliminados.


In [11]:
# Pregunta 8 : intentando modificar los elementos de la tuple para corroborar que no se puede:
print(tuple_1)
tuple_1[0]=100
tuple_1[1]="Argentina"

print(tuple_1[0]=100)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (129615631.py, line 6)

In [12]:
# Pregunta 9: funcion movie_summary

In [13]:
import pandas as pd
import numpy as np

In [14]:
movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

In [15]:
def movie_summary(movies):
    return [f"La película {name} pertenece al género {info['genre']} y fue lanzado en {info['year']}."
            for name, info in movies.items()]

print(movie_summary(movies))

['La película Inception pertenece al género Sci-Fi y fue lanzado en 2010.', 'La película Parasite pertenece al género Drama y fue lanzado en 2019.', 'La película Whiplash pertenece al género Drama y fue lanzado en 2014.']


In [16]:
# Pregunta 10 (Hecha por Eduardo)

In [17]:
# Paso 1 Importamos la la libreria numpy con import
import numpy as np

In [18]:
# Paso2 Generar matriz 4x4 con enteros aleatorios entre 1 y 100 como se indica en el ejercicio
matriz = np.random.randint(1, 101, size=(4, 4))
print("Matriz generada:\n", matriz)

Matriz generada:
 [[83 26 97 88]
 [38 70  2 32]
 [62 67 14 36]
 [17 57 52 23]]


In [19]:
# Paso 3 Calculamos la media por columna
media_columnas = np.mean(matriz, axis=0)
print("\nMedia por columna:", media_columnas)


Media por columna: [50.   55.   41.25 44.75]


In [20]:
# Paso 4 Calculamos la suma de la diagonal principal
suma_diagonal = np.trace(matriz)
print("\nSuma de la diagonal principal:", suma_diagonal)


Suma de la diagonal principal: 190


In [21]:
# Part 3 (Hecho por Georgina) – Pandas Series

In [22]:
# Pregunta 11

From the list of grades [15, 17, 20, 11, 13, 18, 19], create a Pandas Series assigning student names as the index (for example: "Ana", "Jorge", "Valeria", etc.).
A partir de la lista de calificaciones [15, 17, 20, 11, 13, 18, 19], crea una Serie de Pandas asignando nombres de estudiantes como índice (por ejemplo: "Ana", "Jorge", "Valeria", etc.).

In [23]:
import pandas as pd

In [24]:
calificaciones = [15, 17, 20, 11, 13, 18, 19]
nombres = ["Ana", "Jorge", "Valeria", "Mathias","Nancy","Anthony","Rosa"]
alum_calf = pd.Series(calificaciones, index = nombres)
print(alum_calf)

Ana        15
Jorge      17
Valeria    20
Mathias    11
Nancy      13
Anthony    18
Rosa       19
dtype: int64


In [25]:
print(alum_calf.index)

Index(['Ana', 'Jorge', 'Valeria', 'Mathias', 'Nancy', 'Anthony', 'Rosa'], dtype='object')


In [26]:
# Pregunta 12

Using the Series created in the previous step, calculate:

The average of the grades.
The student with the highest grade (use .idxmax()).
The student with the lowest grade (use .idxmin()).
Usando la Serie creada en el paso anterior, calcula:
El promedio de las calificaciones.
El estudiante con la calificación más alta (usa .idxmax()).
El estudiante con la calificación más baja (usa .idxmin()).

In [27]:
promedio = alum_calf.mean()
promedio

16.142857142857142

In [28]:
Alumno = alum_calf.idxmax()
Alumno

'Valeria'

In [29]:
Max = alum_calf.max()
Max

20

In [30]:
Alumno2 = alum_calf.idxmin()
Alumno2

'Mathias'

In [31]:
Min = alum_calf.min()
Min

11

In [32]:
# Pregunta 13

Create a Series from a dictionary of countries and their capitals. Filter and display only those countries whose capital has more than 6 letters. Crea una serie a partir de un diccionario de países y sus capitales. Filtra y muestra solo aquellos países cuya capital tiene más de 6 letras.

In [33]:
Paises_capitales = {
    "Perú":"Lima", 
    "Argentina": "Buenos Aires", 
    "Colombia": "Bogota", 
    "Mexico":"Ciudad de Mexico", 
    "España": "Madrid", 
    "Chile": "Santiago de C"
}
PaisesyCapitales = pd.Series(Paises_capitales)
PaisesyCapitales

Perú                     Lima
Argentina        Buenos Aires
Colombia               Bogota
Mexico       Ciudad de Mexico
España                 Madrid
Chile           Santiago de C
dtype: object

In [34]:
filtro_capitales = PaisesyCapitales[PaisesyCapitales.str.len()>6]
filtro_capitales

Argentina        Buenos Aires
Mexico       Ciudad de Mexico
Chile           Santiago de C
dtype: object

In [35]:
# Para países con mas de 6 letras que son INDEX
filtro_paises = PaisesyCapitales[PaisesyCapitales.index.str.len() > 6]
filtro_paises

Argentina    Buenos Aires
Colombia           Bogota
dtype: object

In [36]:
# Pregunta 14

Create a Series containing several strings and convert all its elements to uppercase using the .apply(str.upper) method. Crea una Serie que contenga varias cadenas y convierte todos sus elementos a mayúsculas utilizando el método .apply(str.upper).

In [37]:
Departamentos = pd.Series(["Lima", "Arequipa", "Cusco", "San Martín", "Ucayali"])
Departamentos

0          Lima
1      Arequipa
2         Cusco
3    San Martín
4       Ucayali
dtype: object

In [38]:
# Convertir todos los elementos a mayúsculas- .apply(str.upper)
Departamentos_may = Departamentos.apply(str.upper)
Departamentos_may

0          LIMA
1      AREQUIPA
2         CUSCO
3    SAN MARTÍN
4       UCAYALI
dtype: object