### Assignment 1 – Part 2: Data Types and Data Structures

#### 6. Declare a variable

In [1]:
variable_int = 20
varible_float = 3.6
variable_str = "Ejercicio 6"
variable_bool = False

In [2]:
print(type(variable_int))
print(type(varible_float))
print(type(variable_str))
print(type(variable_bool))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


#### 7. Create a list 

7.1 Create the list:

In [3]:
list_group2_q7 = [
    "gatos",
    False,
    21,
    12.12,
    ["Lady Gaga", "Kali Uchis"]
]

7.2 Access the first and the last element

In [4]:
#First element
list_group2_q7[0]

'gatos'

In [5]:
#Last element
list_group2_q7[-1]

['Lady Gaga', 'Kali Uchis']

7.3 Add a new string

In [6]:
#Review current elements of my list
list_group2_q7

['gatos', False, 21, 12.12, ['Lady Gaga', 'Kali Uchis']]

In [7]:
#Add a new string element
list_group2_q7.append("perros")

In [8]:
#Verify if the new element has been added
list_group2_q7

['gatos', False, 21, 12.12, ['Lady Gaga', 'Kali Uchis'], 'perros']

7.4 Remove the boolean value

In [9]:
#Review current elements of my list
list_group2_q7

['gatos', False, 21, 12.12, ['Lady Gaga', 'Kali Uchis'], 'perros']

In [10]:
#Remove the boolean value
list_group2_q7.pop(1)

False

In [11]:
#Verify if the boolean value has been removed
list_group2_q7

['gatos', 21, 12.12, ['Lady Gaga', 'Kali Uchis'], 'perros']

#### 8. Define a tuple

8.1 Create a tuple

In [12]:
my_tuple = (
    "peces", 
    True, 
    (6, 96, 87.1)
)
my_tuple

('peces', True, (6, 96, 87.1))

8.2 Why a tuple is immutable?
A tuple is inmutable because the its values cannot be changed once created.

8.3 Try to modify a tuple

In [13]:
#Try to create a new element for the tuple
my_tuple.append("conejos")

AttributeError: 'tuple' object has no attribute 'append'

In [14]:
#Verify is the tuple has been altered
my_tuple

('peces', True, (6, 96, 87.1))

#### 9. Write a Python function named movie_summary

9.1 Create a dictionary

In [15]:
#Dictionary of movies
movies = {
  "Barbie": {"year": 2023, "genre": "Comedy"},
  "Oppenheimer": {"year": 2023, "genre": "Drama"},
  "Super Mario Bros": {"year": 2023, "genre": "Children"}
}

movie_summary = movies
print(movie_summary)

{'Barbie': {'year': 2023, 'genre': 'Comedy'}, 'Oppenheimer': {'year': 2023, 'genre': 'Drama'}, 'Super Mario Bros': {'year': 2023, 'genre': 'Children'}}


In [16]:
type(movie_summary)

dict

In [17]:
movie_summary.keys()

dict_keys(['Barbie', 'Oppenheimer', 'Super Mario Bros'])

In [19]:
movie_summary["Barbie"].get("year")

2023

9.2 Return a list with sentences in an specific format

In [32]:
for title, info in movie_summary.items():
    print(f"{title} belongs to the {info['genre']} genre and was released in {info['year']}")

Barbie belongs to the Comedy genre and was released in 2023
Oppenheimer belongs to the Drama genre and was released in 2023
Super Mario Bros belongs to the Children genre and was released in 2023


#### 10. NumPy number

In [33]:
import numpy as np

10.1 Create the 4x4 Matriz

In [34]:
A = np.array( [ [1, 2, 3, 4], [10, 11, 12, 13], [45, 65, 42, 88], [5, 6, 7, 8] ] )

print(A)

[[ 1  2  3  4]
 [10 11 12 13]
 [45 65 42 88]
 [ 5  6  7  8]]


10.2 Obtain the mean per column

In [36]:
#create the variable column means by defining its structure
column_means = np.mean(A, axis=0)
column_means

array([15.25, 21.  , 16.  , 28.25])

10.3 Obtain the sum of the values in the main diagonal

In [38]:
#Define the main diagonal
diagonal = np.diag(A)
diagonal

array([ 1, 11, 42,  8])

In [39]:
#Create the variable diagonal_sum
diagonal_sum = np.sum(diagonal)
diagonal_sum

62